# Generated by Django 3.0.8 on 2020-07-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthclient',
            name='realm',
            field=models.CharField(default='dev', max_length=255),
            preserve_default=False,
        ),
    ]
